"""Changed profile_picture field to String

Revision ID: 06dd98dad7ca
Revises: e72ec1f95592
Create Date: 2024-08-20 19:35:33.817483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dd98dad7ca'
down_revision = 'e72ec1f95592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=150),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
