"""Initial migration

Revision ID: 4e01511fbc5c
Revises: 0727a24674cb
Create Date: 2024-08-20 17:10:13.204525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e01511fbc5c'
down_revision = '0727a24674cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_notification_thread_id',  # Adding a name to the foreign key constraint
            'thread',  # The referenced table
            ['thread_id'],  # The column in 'notification' table
            ['id']  # The column in 'thread' table
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_thread_id', type_='foreignkey')  # Use the name you provided above
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
